### ISSUE TITLE
How to print table view, like orders details with Items, price and total price

### ISSUE THREAD

**Issue by shubhamdeol** [januslo/react-native-bluetooth-escpos-printer#11]
I can see that we can use print column method, like below 

`await BluetoothEscposPrinter.printColumn(columnWidths,
    [
      BluetoothEscposPrinter.ALIGN.LEFT,
      BluetoothEscposPrinter.ALIGN.CENTER,
      BluetoothEscposPrinter.ALIGN.CENTER,
      BluetoothEscposPrinter.ALIGN.RIGHT,
    ],
    ['Order Id', 'Item', 'Price', 'test'], {});`

my doubt is what is this emoty object parameter in the end. what I can pass into it.

**Comment by januslo** [comment]
that because the options of the printColumn cannot be null or would through some RN exception that we don't expected. I don't know what would cause those problem and no time to figure out that, so just let a empty object as parameters now. May resolve in following version, may not, depends on my time.
```java
  public void printColumn(ReadableArray columnWidths,ReadableArray columnAligns,ReadableArray columnTexts,
                            @Nullable ReadableMap options,final Promise promise)
```

**Comment by januslo** [comment]
the options are the same like printText(), you may find out the parameters via the readme.md
